server: "https://api.kinopoisk.dev"
token: "4F1NQKQ-NH2M1C2-JWKVHR0-XW9DF0J"
request_timeout: 45
endpoints:
  movie:
    path: "movie"
    ver: "v1.4"
  movie_id:
    path: "movie/{id}" # movie/{id}
    ver: "v1.4"
  movie_random:
    path: "movie/random"
    ver: "v1.4"
  movie_search:
    path: "movie/search"
    ver: "v1.4"
  movie_awards:
    path: "movie/awards"
    ver: "v1.4"
  movie_possible_values_by_field:
    path: "movie/possible-values-by-field"
    ver: "v1.4"
  season:
    path: "season"
    ver: "1.4"
  review:
    path: "review"
    ver: "1.4"
  person:
    path: "person"
    ver: "1.4"
  person_id:
    path: "person/{id}"
    ver: "1.4"
  person_search:
    path: "person/search"
    ver: "1.4"
  person_awards:
    path: "person/awards"
    ver: "1.4"
  studio:
    path: "studio"
    ver: "1.4"
  keyword:
    path: "keyword"
    ver: "1.4"
  image:
    path: "image"
    ver: "1.4"
  list:
    path: "list"
    ver: "1.4"
  list_slug:
    path: "list/{slug}"
    ver: "1.4"